services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: telegram_otp_bot
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./logs:/app/logs # Mount thư mục logs từ host vào container
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Giới hạn kích thước log mỗi file
        max-file: "3"    # Số lượng file log tối đa
