services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: telegram_otp_bot
    restart: always
    volumes:
      - ./logs:/app/logs # Mount thư mục logs từ host vào container
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Giới hạn kích thước log mỗi file
        max-file: "3"    # Số lượng file log tối đa
    expose:
      - "5000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl:ro  # Chứng chỉ SSL
    depends_on:
      - flask
    networks:
      - app_network
networks:
  app_network:
    driver: bridge